# Generated by Django 4.2.3 on 2023-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=12)),
                ('event_notification', models.CharField(blank=True, choices=[('all_app_users', 'All App Users'), ('groups', 'Groups')], default=None, max_length=255, null=True)),
                ('event_types', models.CharField(blank=True, choices=[('sos', 'SOS'), ('timer', 'Timer'), ('911', '911'), ('safe_walk', 'Safe WALK')], default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
    ]
