# Generated by Django 4.2.3 on 2023-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contacts', '0003_alter_contacts_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
