# Generated by Django 4.2.3 on 2023-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='groups',
        ),
        migrations.AddField(
            model_name='contacts',
            name='groups',
            field=models.TextField(blank=True, null=True),
        ),
    ]
