# Generated by Django 4.2.3 on 2023-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contacts_groups_contacts_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='groups',
            field=models.CharField(blank=True, choices=[('group1', 'Group1'), ('group2', 'Group2'), ('group3', 'Group3')], default=None, max_length=100, null=True),
        ),
    ]
