# Generated by Django 4.2.3 on 2023-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_groups_alter_contacts_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='groups',
            field=models.ManyToManyField(null=True, to='contacts.groups'),
        ),
    ]
