# Generated by Django 4.2.3 on 2023-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contacts_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.groups'),
        ),
    ]
