# Generated by Django 4.2.3 on 2023-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contacts_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AddField(
            model_name='contacts',
            name='groups',
            field=models.CharField(blank=True, choices=[('group1', 'Group1'), ('group2', 'Group2'), ('group3', 'Group3')], default=None, max_length=255, null=True),
        ),
    ]
