# Generated by Django 4.2.3 on 2023-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_contacts_groups_delete_groups_contacts_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='groups',
        ),
        migrations.AddField(
            model_name='contacts',
            name='groups',
            field=models.ManyToManyField(blank=True, to='contacts.groups'),
        ),
    ]
