# Generated by Django 4.2.3 on 2023-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_groups_remove_contacts_groups_contacts_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='groups',
            field=models.ManyToManyField(related_name='contacts', to='contacts.groups'),
        ),
    ]
