# Generated by Django 4.2.3 on 2023-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_remove_contacts_groups_alter_contacts_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='groups',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
